server:
  port: 8081
  error:
    include-message: always

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dacnpm_nhom_fbt?useUnicode=true&characterEncoding=UTF-8
    password: ""

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true

  jackson:
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false